"use client";
import Link from "next/link";
import { ArrowRight, CalendarDays, CheckCheck, ExternalLink, MapPin, RefreshCw, UserCheck, Users, UsersRound } from "lucide-react";
import { useAdmin } from "@/components/layout/admin-shell";
import { useAdminResource } from "@/hooks/use-admin-resource";
import { Button } from "@/components/ui/button";
import { Alert, EmptyState, Spinner } from "@/components/ui/feedback";
import { Badge } from "@/components/ui/badge";
import { KpiCard } from "@/components/dashboard/kpi-card";
import { CheckinChart } from "@/components/dashboard/checkin-chart";
import { formatDate, formatTime, number } from "@/lib/utils";
import type { DashboardSummary, TrendPoint } from "@/types";

export default function DashboardPage() {
  const { event, invalidate } = useAdmin();
  const summary = useAdminResource<DashboardSummary>("/admin/dashboard/summary");
  const trend = useAdminResource<TrendPoint[]>("/admin/dashboard/checkins");
  const data = summary.data;
  return <div className="space-y-6">
    <div className="flex flex-wrap items-center justify-between gap-4"><div><p className="mb-2 flex items-center gap-2 text-[11px] font-bold uppercase tracking-[0.18em] text-primary"><span className="h-0.5 w-7 bg-brand-red"/>Điều hành sự kiện</p><h1 className="text-3xl font-bold tracking-[-.035em]">Tổng quan</h1></div><div className="flex gap-2"><Button variant="secondary" onClick={invalidate} disabled={summary.loading || trend.loading}><RefreshCw className={summary.loading ? "animate-spin" : ""}/>Làm mới</Button><Button asChild><Link href="/admin/guests"><Users/>Khách mời</Link></Button></div></div>
    <div className="relative flex flex-wrap items-center justify-between gap-4 overflow-hidden rounded-2xl bg-[#123b88] px-6 py-5 text-white shadow-[0_14px_35px_rgba(18,59,136,.18)]"><span className="absolute inset-y-0 left-0 w-1.5 bg-brand-red"/><div><h2 className="text-base font-bold">{event.name}</h2><div className="mt-2 flex flex-wrap gap-x-5 gap-y-2 text-xs text-blue-100/80"><span className="inline-flex items-center gap-1.5"><CalendarDays className="size-3.5"/>{formatDate(event.start_at, { hour: "2-digit", minute: "2-digit" })}</span><span className="inline-flex items-center gap-1.5"><MapPin className="size-3.5"/>{event.venue}</span></div></div><Button asChild variant="secondary" size="sm"><a href={event.welcome_screen_url} target="_blank" rel="noopener noreferrer">Màn hình chào<ExternalLink/></a></Button></div>
    {summary.error && <Alert>{summary.error} Dữ liệu trước đó, nếu có, được giữ lại để đối chiếu.</Alert>}
    {!data ? summary.loading ? <Spinner/> : <EmptyState title="Không tải được tổng quan"><Button onClick={() => void summary.refresh()}>Thử lại</Button></EmptyState> : <>
      <div className="grid gap-4 sm:grid-cols-2 xl:grid-cols-4"><KpiCard label="Tổng khách mời" value={data.total_guests} description="Số thư mời trong danh sách" icon={Users}/><KpiCard label="Xác nhận tham dự" value={data.accepted} description={`${number(data.pending)} chưa phản hồi · ${number(data.declined)} từ chối`} icon={UserCheck}/><KpiCard label="Dự kiến tham dự" value={data.expected_attendance} description="Đã xác nhận, gồm người đi cùng đăng ký" icon={UsersRound}/><KpiCard label="Đã check-in" value={data.checked_in} description={`${number(data.checkin_rate)}% trên tổng số thư mời`} icon={CheckCheck}/></div>
      <div className="grid gap-5 xl:grid-cols-[1.65fr_1fr]"><section className="card-shell rounded-2xl p-6"><div className="flex items-start justify-between gap-3"><div><h2 className="text-base font-bold">Lượt check-in</h2><p className="mt-1 text-xs text-muted">Theo từng 15 phút</p></div><Badge>Realtime</Badge></div>{trend.error && <div className="mt-3"><Alert>{trend.error}</Alert></div>}{trend.data ? <CheckinChart points={trend.data}/> : trend.loading ? <Spinner/> : <p className="py-8 text-center text-sm text-muted">Chưa có dữ liệu.</p>}</section><section className="card-shell rounded-2xl p-6"><h2 className="text-base font-bold">Tiến độ</h2><div className="mt-6 flex items-end justify-between"><span className="text-4xl font-bold tracking-[-.04em]">{number(data.checkin_rate)}<span className="ml-1 text-base text-muted">%</span></span><span className="pb-1 text-xs font-medium text-muted">{number(data.checked_in)} / {number(data.total_guests)}</span></div><div role="progressbar" aria-label="Tỷ lệ check-in" aria-valuenow={data.checkin_rate} aria-valuemin={0} aria-valuemax={100} className="mt-4 h-2.5 overflow-hidden rounded-full bg-blue-50 shadow-inner"><div className="h-full rounded-full bg-gradient-to-r from-primary to-[#3970d5] shadow-[0_0_12px_rgba(36,74,165,.3)] transition-[width] duration-500" style={{ width: `${Math.max(0, Math.min(100, data.checkin_rate))}%` }}/></div><dl className="mt-6 space-y-3.5 text-sm"><div className="flex justify-between"><dt className="text-muted">Chưa đến</dt><dd className="font-bold">{number(data.not_arrived)}</dd></div><div className="flex justify-between"><dt className="text-muted">Đã xác nhận, chưa đến</dt><dd className="font-bold">{number(data.no_show)}</dd></div><div className="flex justify-between border-t border-border pt-3.5"><dt className="text-muted">Quy mô đã đăng ký</dt><dd className="font-bold text-primary">{number(data.registered_arrived)}</dd></div></dl></section></div>
      <section className="card-shell overflow-hidden rounded-2xl"><div className="flex items-center justify-between border-b border-border px-6 py-5"><h2 className="text-base font-bold">Check-in gần nhất</h2><Button asChild variant="ghost" size="sm"><Link href="/admin/guests">Xem danh sách<ArrowRight/></Link></Button></div>{data.recent_checkins.length ? <div className="overflow-x-auto"><table className="w-full text-left text-sm"><thead className="bg-blue-50/60 text-xs font-semibold text-muted"><tr><th className="px-6 py-3 font-semibold">Khách mời</th><th className="px-6 py-3 font-semibold">Đơn vị</th><th className="px-6 py-3 font-semibold">Quầy</th><th className="px-6 py-3 text-right font-semibold">Thời gian</th></tr></thead><tbody>{data.recent_checkins.map((guest) => <tr key={guest.id} className="border-t border-border transition hover:bg-blue-50/40"><td className="whitespace-nowrap px-6 py-4 font-semibold text-foreground">{guest.guest_name}</td><td className="px-6 py-4 text-sm text-muted">{guest.company || "—"}</td><td className="px-6 py-4"><Badge>{guest.counter}</Badge></td><td className="whitespace-nowrap px-6 py-4 text-right text-sm font-medium text-muted tabular-nums">{formatTime(guest.checked_in_at)}</td></tr>)}</tbody></table></div> : <EmptyState title="Sẵn sàng đón khách"/>}</section>
      <section className="card-shell rounded-2xl p-6"><h2 className="text-base font-bold">Theo quầy</h2><div className="mt-4 grid gap-3 sm:grid-cols-2 xl:grid-cols-4">{event.counters.map((counter) => <div key={counter} className="flex items-center justify-between rounded-xl border border-blue-100 bg-blue-50/45 px-4 py-3.5 shadow-inner"><span className="text-xs font-semibold text-primary">{counter}</span><span className="text-base font-bold tabular-nums">{number(data.checkins_by_counter.find((item) => item.counter === counter)?.count || 0)} <span className="text-xs font-normal text-muted">khách</span></span></div>)}</div></section>
    </>}
  </div>;
}
