"use client";
import Link from "next/link";
import { useRef, useState } from "react";
import { ArrowRight, Check, Download, FileSpreadsheet, FileUp, LoaderCircle } from "lucide-react";
import { useAdmin } from "@/components/layout/admin-shell";
import { api, download } from "@/lib/api";
import { number } from "@/lib/utils";
import { Button } from "@/components/ui/button";
import { Alert } from "@/components/ui/feedback";
import { Badge } from "@/components/ui/badge";
import type { ImportPreview } from "@/types";

export default function ImportPage() {
  const { token, invalidate } = useAdmin(); const input = useRef<HTMLInputElement>(null);
  const [file, setFile] = useState<File | null>(null); const [preview, setPreview] = useState<ImportPreview | null>(null);
  const [busy, setBusy] = useState<"preview" | "import" | "template" | null>(null); const [error, setError] = useState<string | null>(null);
  const [result, setResult] = useState<{ imported: number; skipped: number } | null>(null);
  const selectFile = (next: File | null) => { setPreview(null); setResult(null); setError(null); if (next && (!/\.(csv|xlsx)$/i.test(next.name) || next.size > 5 * 1024 * 1024)) { setFile(null); setError("Chọn tệp CSV hoặc XLSX, dung lượng tối đa 5 MB."); if (input.current) input.current.value = ""; return; } setFile(next); };
  const inspect = async () => { if (!file) return; setBusy("preview"); setError(null); setPreview(null); const form = new FormData(); form.append("file", file); try { setPreview(await api<ImportPreview>("/admin/guests/import/preview", { method: "POST", body: form, token })); } catch (err) { setError(err instanceof Error ? err.message : "Không thể kiểm tra tệp."); } finally { setBusy(null); } };
  const commit = async () => { if (!file || !preview || preview.errors.length || !preview.valid_count) return; setBusy("import"); setError(null); const form = new FormData(); form.append("file", file); try { setResult(await api<{ imported: number; skipped: number }>("/admin/guests/import", { method: "POST", body: form, token })); setFile(null); setPreview(null); if (input.current) input.current.value = ""; invalidate(); } catch (err) { setError(err instanceof Error ? err.message : "Không thể nhập danh sách."); } finally { setBusy(null); } };
  return <div className="space-y-6"><div><p className="mb-2 flex items-center gap-2 text-[11px] font-bold uppercase tracking-[0.18em] text-primary"><span className="h-0.5 w-7 bg-brand-red"/>Chuẩn bị dữ liệu</p><h1 className="text-3xl font-bold tracking-[-.035em]">Nhập khách mời</h1></div>
    {error && <Alert>{error}</Alert>}{result && <Alert tone="success"><p>Đã thêm <strong>{number(result.imported)} khách mời</strong>. Bỏ qua {number(result.skipped)} dòng có email trùng.</p><Link href="/admin/guests" className="mt-1 inline-flex items-center gap-1 font-medium underline">Xem danh sách khách mời<ArrowRight className="size-3"/></Link></Alert>}
    <div className="grid gap-6 xl:grid-cols-[1.6fr_1fr]"><section className="card-shell rounded-2xl p-6"><div className="mb-5 flex items-center gap-3"><span className="flex size-8 items-center justify-center rounded-xl bg-primary text-xs font-bold text-white shadow-sm">1</span><h2 className="text-base font-bold">Chọn tệp danh sách</h2></div><label htmlFor="import-file" className="flex min-h-48 cursor-pointer flex-col items-center justify-center rounded-xl border-2 border-dashed border-blue-200 bg-blue-50/35 p-6 text-center transition hover:border-primary hover:bg-blue-50"><span className="mb-4 flex size-12 items-center justify-center rounded-xl bg-white text-primary shadow-sm"><FileUp className="size-6"/></span><span className="text-sm font-semibold">{file ? file.name : "Chọn tệp Excel hoặc CSV"}</span><span className="mt-2 text-xs text-muted">{file ? `${number(file.size / 1024)} KB · Nhấn để đổi tệp` : ".xlsx, .csv · Tối đa 5 MB"}</span><input ref={input} id="import-file" type="file" accept=".csv,.xlsx" className="sr-only" disabled={!!busy} onChange={(event) => selectFile(event.target.files?.[0] || null)}/></label><div className="mt-5 flex flex-wrap items-center justify-between gap-3"><span className="text-xs text-muted">Chỉ lưu sau khi xác nhận.</span><Button onClick={() => void inspect()} disabled={!file || !!busy}>{busy === "preview" ? <LoaderCircle className="animate-spin"/> : <FileSpreadsheet/>}{busy === "preview" ? "Đang kiểm tra…" : "Kiểm tra dữ liệu"}</Button></div></section>
      <aside className="card-shell rounded-2xl p-6"><h2 className="text-base font-bold">Định dạng tệp</h2><p className="mt-3 text-xs leading-6 text-muted">Dòng đầu là tên cột. Chỉ họ tên bắt buộc.</p><div className="mt-4 overflow-hidden rounded-xl border border-border"><table className="w-full text-left text-xs"><tbody>{[["name", "Họ và tên · Bắt buộc"], ["company", "Đơn vị / Công ty"], ["email", "Email"], ["phone", "Số điện thoại"], ["notes", "Ghi chú"]].map(([column,label]) => <tr key={column} className="border-b border-border last:border-0"><td className="bg-blue-50/60 px-3 py-2.5 font-mono text-[11px] font-semibold text-primary">{column}</td><td className="px-3 py-2.5 text-muted">{label}</td></tr>)}</tbody></table></div><Button variant="secondary" className="mt-5 w-full" disabled={!!busy} onClick={() => { setBusy("template"); setError(null); void download("/admin/guests/template.csv", "mau-khach-moi.csv", token).catch((err: unknown) => setError(err instanceof Error ? err.message : "Không tải được tệp mẫu.")).finally(() => setBusy(null)); }}><Download/>Tải tệp mẫu CSV</Button><p className="mt-4 text-[11px] leading-5 text-muted">Email trùng được bỏ qua; khách trùng tên vẫn được thêm riêng.</p></aside></div>
    {preview && <section className="card-shell overflow-hidden rounded-2xl"><div className="flex flex-wrap items-center justify-between gap-4 border-b border-border p-5"><div className="flex items-center gap-3"><span className="flex size-8 items-center justify-center rounded-xl bg-brand-red text-xs font-bold text-white shadow-sm">2</span><h2 className="text-base font-bold">Xem trước và xác nhận</h2></div><div className="flex gap-2"><Badge>{number(preview.total)} dòng</Badge><Badge tone="success">{number(preview.valid_count)} hợp lệ</Badge>{preview.errors.length > 0 && <Badge tone="danger">{number(preview.errors.length)} lỗi</Badge>}</div></div>
      {preview.errors.length > 0 && <div className="m-5"><Alert><p className="font-medium">Sửa các lỗi sau trong tệp và tải lên lại.</p><ul className="mt-2 max-h-48 list-inside list-disc overflow-y-auto">{preview.errors.map((item,index) => <li key={`${item.row_number}-${index}`}>Dòng {item.row_number}: {item.message}</li>)}</ul></Alert></div>}
      <div className="max-h-96 overflow-auto"><table className="w-full text-left text-xs"><thead className="sticky top-0 bg-slate-50 text-muted"><tr>{["Dòng", "Họ và tên", "Đơn vị", "Email", "Điện thoại", "Ghi chú"].map((label) => <th key={label} className="whitespace-nowrap px-5 py-3 font-medium">{label}</th>)}</tr></thead><tbody>{preview.rows.slice(0,100).map((row) => <tr key={row.row_number} className="border-t border-border"><td className="px-5 py-3 text-muted">{row.row_number}</td><td className="whitespace-nowrap px-5 py-3 font-medium">{row.name}</td><td className="px-5 py-3">{row.company || "—"}</td><td className="px-5 py-3 text-muted">{row.email || "—"}</td><td className="px-5 py-3 text-muted">{row.phone || "—"}</td><td className="max-w-64 px-5 py-3 text-muted">{row.notes || "—"}</td></tr>)}</tbody></table></div>
      <div className="flex flex-wrap items-center justify-between gap-4 border-t border-border p-5"><p className="max-w-xl text-xs leading-5 text-muted">{preview.rows.length > 100 ? "Hiển thị 100 dòng đầu. " : ""}Xác nhận để nhập toàn bộ dòng hợp lệ. Mỗi khách mới được cấp đường dẫn thư mời và mã QR riêng.</p><Button onClick={() => void commit()} disabled={!!busy || preview.errors.length > 0 || !preview.valid_count}>{busy === "import" ? <LoaderCircle className="animate-spin"/> : <Check/>}{busy === "import" ? "Đang nhập…" : "Xác nhận nhập danh sách"}</Button></div>
    </section>}
  </div>;
}
