"use client";
import { useMemo, useState } from "react";
import { flexRender, getCoreRowModel, useReactTable, type ColumnDef, type SortingState } from "@tanstack/react-table";
import * as Dropdown from "@radix-ui/react-dropdown-menu";
import { ArrowDown, ArrowUp, ArrowUpDown, Download, ExternalLink, MoreHorizontal, Pencil } from "lucide-react";
import { Badge } from "@/components/ui/badge";
import { Button } from "@/components/ui/button";
import { Alert, EmptyState } from "@/components/ui/feedback";
import { download } from "@/lib/api";
import { formatDate, formatTime, number } from "@/lib/utils";
import { useAdmin } from "@/components/layout/admin-shell";
import type { Guest } from "@/types";

export type GuestTableMode = "invitation" | "checkin";
const rsvpLabels = { pending: "Chưa phản hồi", accepted: "Đã xác nhận", declined: "Từ chối" };

export function GuestTable({ mode, guests, sorting, onSortingChange, onEdit }: { mode: GuestTableMode; guests: Guest[]; sorting: SortingState; onSortingChange: (sorting: SortingState) => void; onEdit: (guest: Guest) => void }) {
  const { token } = useAdmin(); const [error, setError] = useState<string | null>(null); const [downloading, setDownloading] = useState<number | null>(null);
  const actions = useMemo<ColumnDef<Guest>>(() => ({ id: "actions", header: "", enableSorting: false, cell: ({ row }) => <Dropdown.Root><Dropdown.Trigger asChild><Button variant="ghost" size="icon" aria-label={`Thao tác với ${row.original.name}`} disabled={downloading === row.original.id}><MoreHorizontal/></Button></Dropdown.Trigger><Dropdown.Portal><Dropdown.Content align="end" sideOffset={6} className="z-40 min-w-48 rounded-lg border border-border bg-white p-1 shadow-[0_8px_24px_rgba(15,23,42,.12)]"><Dropdown.Item className="flex cursor-pointer items-center gap-2 rounded-md px-3 py-2.5 text-xs font-medium outline-none focus:bg-slate-100 focus:text-primary" onSelect={() => onEdit(row.original)}><Pencil className="size-3.5"/>Chỉnh sửa</Dropdown.Item><Dropdown.Item asChild><a className="flex cursor-pointer items-center gap-2 rounded-md px-3 py-2.5 text-xs font-medium outline-none focus:bg-slate-100 focus:text-primary" href={row.original.invitation_url} target="_blank" rel="noopener noreferrer"><ExternalLink className="size-3.5"/>Mở thư mời</a></Dropdown.Item><Dropdown.Item className="flex cursor-pointer items-center gap-2 rounded-md px-3 py-2.5 text-xs font-medium outline-none focus:bg-slate-100 focus:text-primary" onSelect={() => { setError(null); setDownloading(row.original.id); void download(`/admin/guests/${row.original.id}/qr.png`, `qr-${row.original.id}.png`, token).catch((err: unknown) => setError(err instanceof Error ? err.message : "Không tải được QR.")).finally(() => setDownloading(null)); }}><Download className="size-3.5"/>Tải mã QR</Dropdown.Item></Dropdown.Content></Dropdown.Portal></Dropdown.Root> }), [downloading, onEdit, token]);
  const columns = useMemo<ColumnDef<Guest>[]>(() => mode === "invitation" ? [
    { accessorKey: "name", header: "Khách mời", cell: ({ row }) => <div className="min-w-36 sm:min-w-44"><button className="text-left font-semibold text-foreground transition hover:text-primary hover:underline" onClick={() => onEdit(row.original)}>{row.original.name}</button><p className="mt-1 text-xs text-muted">{row.original.company || "Chưa có đơn vị"}</p><p className="mt-1 max-w-40 truncate text-[11px] text-slate-400 sm:hidden">{row.original.email || row.original.phone || "Chưa có liên hệ"}</p><p className="mt-1 text-[11px] font-semibold text-primary sm:hidden">Số người thân: {row.original.companions}</p>{row.original.notes && <p className="mt-1 max-w-40 truncate text-[11px] text-slate-500 sm:hidden">{row.original.notes}</p>}</div> },
    { id: "contact", header: "Liên hệ", enableSorting: false, cell: ({ row }) => <div className="min-w-44 text-xs leading-5 text-muted"><p>{row.original.email || "—"}</p><p>{row.original.phone || "—"}</p></div> },
    { accessorKey: "rsvp_status", header: "Phản hồi", enableSorting: false, cell: ({ row }) => <Badge tone={row.original.rsvp_status === "accepted" ? "success" : row.original.rsvp_status === "declined" ? "neutral" : "warning"}>{rsvpLabels[row.original.rsvp_status]}</Badge> },
    { accessorKey: "companions", header: "Số người thân", enableSorting: false, cell: ({ row }) => <span className="whitespace-nowrap font-bold text-foreground">{number(row.original.companions)}</span> },
    { accessorKey: "notes", header: "Ghi chú khách gửi", enableSorting: false, cell: ({ row }) => <p className="max-w-52 text-xs leading-5 text-muted" title={row.original.notes}>{row.original.notes || "—"}</p> },
    { accessorKey: "created_at", header: "Ngày tạo", cell: ({ row }) => <span className="whitespace-nowrap text-xs font-medium text-muted">{formatDate(row.original.created_at)}</span> },
    actions,
  ] : [
    { accessorKey: "name", header: "Khách đã xác nhận", cell: ({ row }) => <div className="min-w-36 sm:min-w-48"><button className="text-left font-semibold text-foreground transition hover:text-primary hover:underline" onClick={() => onEdit(row.original)}>{row.original.name}</button><p className="mt-1 text-xs text-muted">{row.original.company || "Chưa có đơn vị"}</p><p className="mt-1 text-[11px] font-semibold text-primary sm:hidden">{number(1 + row.original.companions)} người đăng ký</p></div> },
    { id: "attendance", header: "Đăng ký", enableSorting: false, cell: ({ row }) => <div className="min-w-24"><p className="font-bold text-foreground">{number(1 + row.original.companions)} người</p><p className="mt-1 text-xs text-muted">{row.original.companions ? `Có ${row.original.companions} đi cùng` : "Không đi cùng"}</p></div> },
    { accessorKey: "checked_in_at", header: "Trạng thái", cell: ({ row }) => row.original.checked_in_at ? <div><Badge tone="success">Đã check-in</Badge><p className="mt-1.5 whitespace-nowrap text-xs font-medium text-muted">{formatTime(row.original.checked_in_at)}</p></div> : <Badge tone="warning">Chưa đến</Badge> },
    { id: "counter", header: "Quầy", enableSorting: false, cell: ({ row }) => <span className="text-xs font-semibold text-primary">{row.original.counter || "—"}</span> },
    actions,
  ], [mode, onEdit, actions]);
  // TanStack Table intentionally returns dynamic table methods; it does not use React Compiler memoization.
  // eslint-disable-next-line react-hooks/incompatible-library
  const table = useReactTable({ data: guests, columns, getCoreRowModel: getCoreRowModel(), manualSorting: true, state: { sorting }, onSortingChange: (updater) => onSortingChange(typeof updater === "function" ? updater(sorting) : updater), enableSortingRemoval: false });
  const responsiveColumns = mode === "invitation"
    ? "[&_th:nth-child(2)]:hidden [&_td:nth-child(2)]:hidden [&_th:nth-child(4)]:hidden [&_td:nth-child(4)]:hidden [&_th:nth-child(5)]:hidden [&_td:nth-child(5)]:hidden [&_th:nth-child(6)]:hidden [&_td:nth-child(6)]:hidden sm:[&_th:nth-child(4)]:table-cell sm:[&_td:nth-child(4)]:table-cell md:[&_th:nth-child(2)]:table-cell md:[&_td:nth-child(2)]:table-cell md:[&_th:nth-child(5)]:table-cell md:[&_td:nth-child(5)]:table-cell lg:[&_th:nth-child(6)]:table-cell lg:[&_td:nth-child(6)]:table-cell"
    : "[&_th:nth-child(2)]:hidden [&_td:nth-child(2)]:hidden [&_th:nth-child(4)]:hidden [&_td:nth-child(4)]:hidden sm:[&_th:nth-child(2)]:table-cell sm:[&_td:nth-child(2)]:table-cell lg:[&_th:nth-child(4)]:table-cell lg:[&_td:nth-child(4)]:table-cell";
  return <>{error && <div className="m-4"><Alert>{error}</Alert></div>}<div className="max-h-[calc(100dvh-19rem)] overflow-auto bg-white"><table className={`w-full text-left text-sm ${responsiveColumns}`}><thead className="sticky top-0 z-10 bg-slate-50">{table.getHeaderGroups().map((group) => <tr key={group.id}>{group.headers.map((header) => <th key={header.id} className="px-3 py-3 text-xs font-semibold text-slate-600 sm:px-5">{header.column.getCanSort() ? <button className="inline-flex items-center gap-1.5 whitespace-nowrap" onClick={header.column.getToggleSortingHandler()}>{flexRender(header.column.columnDef.header, header.getContext())}{header.column.getIsSorted() === "asc" ? <ArrowUp className="size-3"/> : header.column.getIsSorted() === "desc" ? <ArrowDown className="size-3"/> : <ArrowUpDown className="size-3 text-slate-400"/>}</button> : flexRender(header.column.columnDef.header, header.getContext())}</th>)}</tr>)}</thead><tbody>{table.getRowModel().rows.map((row) => <tr key={row.id} className="border-t border-border transition-colors hover:bg-slate-50">{row.getVisibleCells().map((cell) => <td key={cell.id} className="px-3 py-3 sm:px-5">{flexRender(cell.column.columnDef.cell, cell.getContext())}</td>)}</tr>)}</tbody></table></div>{!guests.length && <EmptyState title={mode === "checkin" ? "Chưa có khách xác nhận tham dự" : "Không có khách mời phù hợp"} description={mode === "checkin" ? "Khách sẽ xuất hiện tại đây ngay khi xác nhận thư mời." : "Thử thay đổi bộ lọc hoặc thêm khách mới."}/>}</>;
}
